apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"2"},"creationTimestamp":"2025-01-22T19:54:29Z","generation":2,"name":"synergychat-crawler","namespace":"default","resourceVersion":"13870","uid":"0bd4fc1e-901a-46e3-8e8f-5fcc0d0d6050"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"synergychat-crawler"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"synergychat-crawler"}},"spec":{"containers":[{"envFrom":[{"configMapRef":{"name":"synergychat-crawler-configmap"}}],"image":"bootdotdev/synergychat-crawler:latest","imagePullPolicy":"Always","name":"synergychat-crawler-1","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/cache","name":"cache-volume"}]},{"envFrom":[{"configMapRef":{"name":"synergychat-crawler-configmap"}}],"image":"bootdotdev/synergychat-crawler:latest","imagePullPolicy":"Always","name":"synergychat-crawler-2","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/cache","name":"cache-volume"}]},{"envFrom":[{"configMapRef":{"name":"synergychat-crawler-configmap"}}],"image":"bootdotdev/synergychat-crawler:latest","imagePullPolicy":"Always","name":"synergychat-crawler-3","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/cache","name":"cache-volume"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"emptyDir":{},"name":"cache-volume"}]}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2025-01-22T22:17:24Z","lastUpdateTime":"2025-01-22T22:17:24Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2025-01-22T19:54:29Z","lastUpdateTime":"2025-01-22T22:17:24Z","message":"ReplicaSet \"synergychat-crawler-779974cb4c\" is progressing.","reason":"ReplicaSetUpdated","status":"True","type":"Progressing"}],"observedGeneration":2,"readyReplicas":1,"replicas":2,"unavailableReplicas":1,"updatedReplicas":1}}
  creationTimestamp: "2025-01-22T19:54:29Z"
  generation: 3
  name: synergychat-crawler
  namespace: crawler
  resourceVersion: "14858"
  uid: 0bd4fc1e-901a-46e3-8e8f-5fcc0d0d6050
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: synergychat-crawler
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: synergychat-crawler
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: synergychat-crawler-configmap
        image: bootdotdev/synergychat-crawler:latest
        imagePullPolicy: Always
        name: synergychat-crawler-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /cache
          name: cache-volume
      - env:
        - name: CRAWLER_PORT
          valueFrom:
            configMapKeyRef:
              name: synergychat-crawler-configmap
              key: CRAWLER_PORT_2
        - name: CRAWLER_KEYWORDS
          valueFrom:
            configMapKeyRef:
              name: synergychat-crawler-configmap
              key: CRAWLER_KEYWORDS  
        - name: CRAWLER_DB_PATH
          valueFrom:
            configMapKeyRef:
              name: synergychat-crawler-configmap
              key: CRAWLER_DB_PATH
        image: bootdotdev/synergychat-crawler:latest
        imagePullPolicy: Always
        name: synergychat-crawler-2
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /cache
          name: cache-volume
      - env:
        - name: CRAWLER_PORT
          valueFrom:
            configMapKeyRef:
              name: synergychat-crawler-configmap
              key: CRAWLER_PORT_3
        - name: CRAWLER_KEYWORDS
          valueFrom:
            configMapKeyRef:
              name: synergychat-crawler-configmap
              key: CRAWLER_KEYWORDS  
        - name: CRAWLER_DB_PATH
          valueFrom:
            configMapKeyRef:
              name: synergychat-crawler-configmap
              key: CRAWLER_DB_PATH
        image: bootdotdev/synergychat-crawler:latest
        imagePullPolicy: Always
        name: synergychat-crawler-3
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /cache
          name: cache-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: cache-volume
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-01-22T22:17:24Z"
    lastUpdateTime: "2025-01-22T22:17:24Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-01-22T22:33:21Z"
    lastUpdateTime: "2025-01-22T22:33:21Z"
    message: ReplicaSet "synergychat-crawler-779974cb4c" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 2
  unavailableReplicas: 1
  updatedReplicas: 1
